// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmpmvzovovngvbrnkacr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtcG12em92b3ZuZ3Zicm5rYWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMzg1NDAsImV4cCI6MjA4NzgxNDU0MH0.Jj7Ehp6679Zqkm7cPOo3MQsBxXcLb8V_XlFRr4WlhMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});